### ISSUE TITLE
cannot concatenate 'str' and 'NoneType' objects 

### ISSUE THREAD

**Issue by pybride** [TimKam/sphinx-pretty-searchresults#1]
Hi,

Thanks for this extension, it is what we need.
Unfortunately, it isn't working:

[sphinx-err-rmic8m.log.txt](https://github.com/TimKam/sphinx-pretty-searchresults/files/396345/sphinx-err-rmic8m.log.txt)

I tried to remove `'-D' 'language=' + language` as I don't need I18N, but then I get:

 [sphinx-err-3cju9l.log.txt](https://github.com/TimKam/sphinx-pretty-searchresults/files/396346/sphinx-err-3cju9l.log.txt)

Best regards,
Pierre-Yann

**Comment by TimKam** [comment]
Thanks for your report. Might be an issue that just occurs on Windows.
It would be great if you could verify/falsify this assumption.

In any case, I'll have a look later today.

**Comment by TimKam** [comment]
I was wrong with my assumption. There were two issues:
1) The build failed if you didn't specify a language in the config file.
2) The build assumed `.` is the source directory and failed if this wasn't true.

Can you confirm that it works now for you, @pybride ?

**Comment by pybride** [comment]
As I'm using a French Windows today, I have now another issue:

Exception occurred:
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier spÚcifiÚ est introuvable
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\sphinx-build.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\sphinx\__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "c:\python27\lib\site-packages\sphinx\__init__.py", line 92, in build_main
    return cmdline.main(argv)
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 284, in main
    tbpath = save_traceback(app)
  File "c:\python27\lib\site-packages\sphinx\util\__init__.py", line 255, in save_traceback
    os.write(fd, exc_format.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 920: ordinal not in range(128)

It seems a common problem with Popen on Windows, but I don't even know which string is creating the issue. I printed some variables:
('project_path', 'c:\\python27\\lib\\site-packages')
('srcdir', u'd:\\Projects\\Platypus\\Main\\Doc\\Sphinx')
('sources_build_path', '../_build_txt')

**Comment by TimKam** [comment]
For a quick fix, you can try adding these line below line 41 of `__init__.py`:

    if isinstance(srcdir, unicode):
        srcdir = srcdir.encode('UTF-8')

I'll see if I can reproduce your issue on a Windows machine later.

**Comment by pybride** [comment]
It doesn't resolve the issue.

**Comment by TimKam** [comment]
I could reproduce the issue on a Windows machine and fix it (for me).
Can you confirm, @pybride ?

**Comment by pybride** [comment]
I'm using a English Windows today, therefore I don't expect the same issues.
But it is still not working.
First, I don't get the 1.3 version (pip install sphinxprettysearchresults --upgrade give me 1.2)
Then, I have now "The system cannot find the file specified", even when copying manually version 1.3

[sphinx-err-njbgj6.log.txt](https://github.com/TimKam/sphinx-pretty-searchresults/files/401022/sphinx-err-njbgj6.log.txt)

Some print out:
('srcdir', 'd:\\Projects\\Platypus\\Main\\Doc\\Sphinx')
('sources_build_path', '../_build_txt')

I got the _build_txt folder, but a level above my sphinx data and make.bat. Shouldn't it be on the same level as _build?
I change to `sources_build_path = '_build_txt'`, but I don't have more success.

**Comment by TimKam** [comment]
The [current version on PyPi](https://pypi.python.org/pypi/sphinxprettysearchresults/0.1.3) is 0.1.3, so I can't understand why it doesn't do the update for you.
I'll try to reproduce the 2nd issue asap.

**Comment by TimKam** [comment]
@pybride :

I couldn't reproduce these issues on my Windows machine.
Could you check which of the directories doesn't exist?

You can add the following line before the `build_txt = ...` line:

  ```
 print 'isdir sources_build_path: ' + os.path.isdir(sources_build_path)
 print 'isdir srcdir: ' + os.path.isdir(srcdir)
```
The exact sphinx-build command you use might also be relevant.

I changed the sources build path to `_build_txt`(removed the `../`), but did not release this, yet.

**Comment by pybride** [comment]
Finally, I could run it, but only with:

`build_txt = subprocess.Popen(['c:\Python27\Scripts\sphinx-build', '-a', '-b', 'text','-D' 'language=' + language, srcdir, sources_build_path])`

I need the full path to sphinx-build.

**Comment by TimKam** [comment]
Thanks for the info, I'll work on a fix

**Comment by pybride** [comment]
Maybe the issue is related to how we install Python. As we only use it for sphinx, Python.exe **isn't** put in the PATH, therefore, for example, pip only work from c:\Python27\Scripts (or if the full path is used).

Also, the make.bat created by sphinx has these lines:
`if "%SPHINXBUILD%" == "" (
	set SPHINXBUILD="c:\Python27\Scripts\sphinx-build"
)`

**Comment by TimKam** [comment]
Because I can't reproduce any related errors, I'll close this issue. Please ask me to re-open if you still experience problems.

**Comment by pybride** [comment]
We updated to 0.3.1, but we still need to change the Popen line to make it work. And it happens on several machines (Windows 10 Pro/Enterprise English)

`build_txt = subprocess.Popen(['c:\Python27\Scripts\sphinx-build', '-a', '-b', 'text','-D' 'language=' + language, srcdir, sources_build_path])`

**Comment by TimKam** [comment]
Is your project OS or can you provide a minimal working example that allows me to reproduce this issue?

**Comment by pybride** [comment]
Not open source. As we are now working on the release, I will try to create a working example in the next few days.

**Comment by TimKam** [comment]
Thanks, I'll have a look then

**Comment by pybride** [comment]
Here is a very simple project, which also has the issue on **make html**. I also put the log file in it.

[sphinx-pretty-searchresults bug on windows.zip](https://github.com/TimKam/sphinx-pretty-searchresults/files/1114274/sphinx-pretty-searchresults.bug.on.windows.zip)
